Module ue-yandex-maps with component and webpack building.
universal-editor/yandex-maps pull request #2
Opened 2017-03-01 14:17 UTC by AlekseySorokin

1. Построена полноценная сборка на webpack;
2. Добавлена демка для тестов компонента;
3. Переработана логика компонента (ue-yandex-maps). 
4. Переписана документация.

2017-03-02 20:36 UTC, niksamokhvalov requested changes
Надо поработать над внешним видом. И хотелось бы везде (даже в демке), кроме документации, видеть только английский язык.

2017-03-02 20:36 UTC, niksamokhvalov commented on dist/index.html
> +    <ul class="nav nav-tabs">
А зачем нам тут табы? Демка же простая, разделы не нужны.

2017-03-02 20:36 UTC, niksamokhvalov commented on dist/components.controller.js
> +                                    mapCenter: [37.620393, 55.765575],
Убери эту настройку, что бы убедиться, что значение по-умолчанию корректно проставляется. Оставь её только у одного какого-нибудь примера, но только не Москву, а что-нибудь другое.

2017-03-02 20:36 UTC, niksamokhvalov commented on dist/components.controller.js
> +                                    mapWidth: 400,
Убери параметры размеров, оставь какие-нибудь необычные размеры только у одного компонента.

И давай сделаем по-умолчанию карту размерами 650 на 400 пикс.

2017-03-02 20:36 UTC, niksamokhvalov commented on docs/ru/README.md
> +| expandable | string | Требуется ли дополнительно запрашивать это поле у бекенда. | + | - |
Поправка, не у бекенда, а сервера.

2017-03-02 20:36 UTC, niksamokhvalov commented on package.json
> +  "name": "universal-editor",
Название, описание — некорректные.

2017-03-06 15:14 UTC, AlekseySorokin commented on dist/index.html
> +    <ul class="nav nav-tabs">
+

2017-03-07 08:12 UTC, niksamokhvalov requested changes

2017-03-07 08:12 UTC, niksamokhvalov commented on package.json
> +  "name": "yandex-maps",
Почему в bower.json `ue-yandex-maps`, а здесь просто `yandex-maps`?

2017-03-07 08:34 UTC, AlekseySorokin commented on package.json
> +  "name": "yandex-maps",
ага. сейчас поправлю.

2017-03-07 08:35 UTC, AlekseySorokin commented on package.json
> +  "name": "yandex-maps",
Сделано.

2017-03-07 09:03 UTC, merged