Change settings for address
universal-editor/yandex-maps pull request #5
Opened 2017-05-24 09:34 UTC by Sergey73

2017-06-15 12:57 UTC, niksamokhvalov requested changes

2017-06-15 12:57 UTC, niksamokhvalov commented on demo/components.controller.js
> +         $rootScope.$on('ue-yandex-maps: setAddress', function(event, value) {
1. Почему название события через пробел? По-моему он лишний тут.
1. В документации **обязательно** должны быть задокументированы все события.

2017-11-24 15:08 UTC, AlekseySorokin commented on demo/components.controller.js
> +         $rootScope.$on('ue-yandex-maps: setAddress', function(event, value) {
Пробел убрал. Но в доке есть упоминание о нем. Смержил с мастером.

2017-11-24 15:10 UTC, AlekseySorokin approved these changes

2017-12-01 09:25 UTC, niksamokhvalov approved these changes

2017-12-15 13:09 UTC, merged